on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: '45 13 * * *'

name: Semgrep

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      GITHUB_PAT: ${{ secrets.PAT_YOGENDRASRIVASTAVA }}  # Add the PAT secret here
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Running semgrep"
          semgrep ci
      - name: Approve PR if Semgrep passes
        if: success()
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_NUMBER=${{ github.event.pull_request.number }}
            PR_REPO=${{ github.repository }}
            GITHUB_API_URL="https://api.github.com/repos/${PR_REPO}/pulls/${PR_NUMBER}/reviews"
            REVIEW_PAYLOAD=$(echo '{"event":"APPROVE"}')
            
            python3 -c "
import requests
import os

url = os.environ['GITHUB_API_URL']
token = os.environ['PAT_YOGENDRASRIVASTAVA']
payload = os.environ['REVIEW_PAYLOAD']

headers = {
    'Authorization': f'token {token}',
    'Accept': 'application/vnd.github.v3+json'
}

response = requests.post(url, headers=headers, data=payload)
response.raise_for_status()
print('Pull request approved.' if response.status_code == 200 else 'Failed to approve pull request.')
"
